admin_users:
    path: /admin/users
    controller: App\Controller\AdminController::index

admin_user_new:
    path: /admin/user/new
    controller: App\Controller\AdminController::new

admin_user_edit:
    path: /admin/user/{id}
    controller: App\Controller\AdminController::edit

admin_user_delete:
    path: /admin/user/{id}/delete
    controller: App\Controller\AdminController::delete

admin_reservations:
    path: /admin/reservations
    controller: App\Controller\AdminController::manageReservations
